### ISSUE TITLE
Just a const wrong? it works fine but ide gives warning

### ISSUE THREAD

**Issue by VanderSP** [uinosoft/t3d.js#1]
382 │   const val   = (fbits & 0x7fffffff) + 0x1000; // rounded value
          ╵         ~~~

Build failed with 1 error:
examples/jsm/textures/IDWMapGenerator.js:401:1: ERROR: Cannot assign to "val" because it is a constant

for now i changed it to let :D

i just copied the examples folder to my project, since i dunno how to alias subimport on non published npm

**Comment by shawn0326** [comment]
Yes, this is actually a bug. Good catch and I will fix this bug.

The npm package is expected to be released in the next two weeks.
But if you want to import it as a local package and use build tools like rollup and webpack, you may be able to solve the alias problem of 't3d' with the help of plugins like `@rollup/plugin-alias`, or webpack `resolve` settings...？

**Comment by VanderSP** [comment]
No problem, i wait npm.. im prototyping ;)

**Comment by VanderSP** [comment]
Maybe thanks to vite, because in webpack i can import submodules without alias, in vite no way, maybe with plugins.... so i dropped the folder...
but i dunno if i drop with webpack it would check that also, because i didn´t imported idw.. idk even what´s idw map. lol, i see the example looks thermal stuff but i can be wrong :D
