### ISSUE TITLE
可以和threejs 混合开发吗

### ISSUE THREAD

**Issue by ghost** [uinosoft/t3d.js#19]

**Comment by shawn0326** [comment]
混合开发的形式很多，我猜您指的是混合渲染，即两个渲染引擎同时操作同一个Canvas的3D上下文。
t3d的renderPass上提供了setTextureExternal与setRenderBufferExternal两个接口，允许外部插入glTexture与glRenderBuffer对象。借由这两个接口，理论上是可以融合不同渲染引擎的两个RenderTarget（渲染结果）的。t3d曾经实践过与cesium混合渲染，并已经证实是可行的。但真的要实现混合渲染，可能还需要修改threejs的部分代码，并对threejs引擎有深入的了解，因为threejs本身是无法直接与其它引擎混合渲染的（无法拿到内部的gl资源对象），因此实现起来还是比较复杂的。
