### ISSUE TITLE
how to render msdf text?

### ISSUE THREAD

**Issue by russelgal** [uinosoft/t3d.js#21]

**Comment by shawn0326** [comment]
For real-time rendering, please refer to this example: https://uinosoft.github.io/t3d.js/examples/#text_sdf. If you're asking about generating MSDF text resources, you can utilize third-party libraries such as: https://github.com/leochocolat/three-msdf-text-utils.

**Comment by russelgal** [comment]
but the texture of one character is simply rendered there https://uinosoft.github.io/t3d.js/examples/#text_sdf
what about the strings?
tried to adapt classes from https://github.com/leochocolat/three-msdf-text-utils to [t3d.js](https://github.com/uinosoft/t3d.js) - unsuccessfully
// so far I am an absolute beginner in webgl

**Comment by shawn0326** [comment]
> https://github.com/leochocolat/three-msdf-text-utils

Seems like a great solution. Thanks for sharing. However, porting it to t3d might take some time.

**Comment by russelgal** [comment]
any ETA of msdf font/text shader? )

**Comment by shawn0326** [comment]
Maybe add a example in the next week or two.

**Comment by shawn0326** [comment]
Maybe add a example in the next week or two.

**Comment by shawn0326** [comment]
merged to dev: https://uinosoft.github.io/t3d.js/examples/#text_bitmap
@russelgal
