### ISSUE TITLE
geometry extrude by Path

### ISSUE THREAD

**Issue by xjindf** [uinosoft/t3d.js#22]
I noticed that the library contains the ExtraceShapeBuilder class. How to implement the extension of 2D sections along a path, similar to the ExtraceGeometry in three. js

**Comment by shawn0326** [comment]
Currently, ExtrudeShapeBuilder does not support path extrude yet. If you want to implement it by yourself, the logic should be similar to TubeBuilder, the difference is that the simple circular cross-section is replaced by Shape.

**Comment by shawn0326** [comment]
The feature has been merged into dev in ExtrudeShapeBuilder
