### ISSUE TITLE
difference with threejs?

### ISSUE THREAD

**Issue by coderofsalvation** [uinosoft/t3d.js#23]
amazing work.

how does this compare & contrast with threejs?
There must be some different philosophy here right?

**Comment by VanderSP** [comment]
It´s inspired in THREEJS, so nothing really changes in fundamental, just some small thing here and there, but it´s not a clone...
It´s a lighter version contrasting with THREE more full featured / bloated
I like both, so I use T3D in back renderer, while THREE at the top

**Comment by shawn0326** [comment]
Thank you for your interest in t3d.js.
Compared to three.js, t3d.js is designed to be more lightweight with fewer APIs, but with the intention to empower developers to do more. Most of the improvements made in line with this philosophy are quite subtle, with the most significant change being the renderer. T3D provides a more extensible way of rendering, which I believe is better suited for future migration to WebGPU rendering.
