### ISSUE TITLE
Some general questions

### ISSUE THREAD

**Issue by VanderSP** [uinosoft/t3d.js#4]
1 - Is intentional that envmap illumination is black, if there´s no at least a light added even with 0.1...? or just envmap would just be enough?

2 - I´ve got a feeling that glossinessmap isn´t working, if i set glossiness 1, it reflects... im ok with metalness workflow, i was just testing and wondering why

3 - When setting an alphaMap to mask, it´s needed to trigger alphaTest even if it´s with 0.01 value... it should be a bit more automatic?  like some default value for alphaTest?

4 - I know you used plane as first to 2d orto... but it´s just a suggestion: as people came from other libs like threejs, they can run in a very bad nightmare needing to do plane.euler.x = Math.PI / 2 :D

**Comment by VanderSP** [comment]
regarding 1 - i found that white pbr textures is too dark, if i don´t use some kind of illumination, as if the envmap was too weak to illuminate the white...

**Comment by shawn0326** [comment]
Questions 1 and 2: We will do some tests later to test these questions.
Question 3: If there is alpha information in the texture, the user has 3 options: set transparent=true to use alpha color blending; use alphaTest; use alphaToCoverage. t3d probably shouldn't do anything by default, like threejs does.
Question 4: I'm not sure if the Plane of all 3D engines face forward by default, but it seems that both threejs and babylonjs are, maybe it's a good idea to change t3d to be consistent with them.

**Comment by VanderSP** [comment]
aaaah you are right! i forgot to do transparent = true, so i dont need alpha 0.01... and it looks so much more smooth now! lol

thanks!

**Comment by VanderSP** [comment]
And about that question about envmap position, blender deforms but, if you think about a cube that u can take 6 camera capture, like doing those traditional rooms for capturing, it works fine for position for example y position... also i found that actually rotating the anchor in 2 axis is very strange... i used this

```
let rotationMatrix1 = new t3d.Matrix4()
rotationMatrix1.makeRotationAxis(new t3d.Vector3(1, 0, 0), 1.85)

let rotationMatrix2 = new t3d.Matrix4()
rotationMatrix2.makeRotationAxis(new t3d.Vector3(0, 0, 1), -0.8)

let combinedMatrix = new t3d.Matrix4()
combinedMatrix.multiply(rotationMatrix1)
combinedMatrix.multiply(rotationMatrix2)

scene.anchorMatrix = combinedMatrix
```

**Comment by VanderSP** [comment]
(question 4) - yeah the plane laid by default can be shocking as it´s invisible... think about z camera and lights for a new bie + instead rotation is euler with axis inverted lol, i think that the convention for rotation is rotation instead euler... and x instead y

**Comment by VanderSP** [comment]
Cool you npm released! thanks!
Many progresses here... :)

Hey, did u forgot to put repeat method on texture?

**Comment by shawn0326** [comment]
The uv transform related properties of the texture are transferred to the material, which is convenient for sharing the texture.
````
material.diffuseMapTransform.setUvTransform(
  offsetX, offsetY, repeatX, repeatY, rotation, centerX, centerY);
````
Refer to this demo: https://uinosoft.github.io/t3d.js/examples/#material_texture_uvtransform

**Comment by VanderSP** [comment]
thanks, i feel that something was changed over place, interesting...

actually i´ve ran in a funny issue in a ring of boxes like objects, i placed another ring of planes over it.. so the objects one are geometry merged, but the planes one is feeded each one with a texture.. i used containers to keep the planes ring right positioned, the funny thing is, when i look into some that was rotated to right, its ok... but the ones in the left.. i see a black little space that i just dont know where it cames... lol

**Comment by VanderSP** [comment]
Discord!
